on:
  push:
    branches: 
      - master
  pull_request:

name: Tests

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-node@v2
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v1
        with:
          cache-on-failure: true
      - name: Install turbodapp
        run: cargo install --git https://github.com/gakonst/dapptools-rs

      - name: Build deps
        run: ./build.sh lootloose

      - name: Run integration tests
        run: ./test.sh lootloose
        # Enable this if using forking tests
        # env:
        #  ETH_RPC_URL: https://eth-mainnet.alchemyapi.io/v2/${{ secrets.ALCHEMY_API_KEY }}
