on:
  push:
    branches:
      - master
  pull_request:

name: e2e tests

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: ["lootloose", "solmate", "vaults", "geb", "solidity-stringutils", "multicall", "guni-lev"]

    env:
      TURBODAPP_REVISION: 3184f05a6d067e20c86de8813bedfed3cd2036bb
      ETH_RPC_URL: https://mainnet.infura.io/v3/c60b0bb42f8a4c6481ecd229eddaca27

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-node@v2
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v1
        with:
          cache-on-failure: true

      # try to get turbodapp from cache
      - name: Cache turbodapp
        id: cache-turbodapp
        uses: actions/cache@v2
        env:
          cache-name: cache-turbodapp
        with:
          path: ~/.cargo/bin/dapp
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ env.TURBODAPP_REVISION }}

      # if couldn't get, install turbodapp
      - name: Install turbodapp
        if: steps.cache-turbodapp.outputs.cache-hit != 'true'
        run: cargo install --git https://github.com/gakonst/dapptools-rs --rev ${{ env.TURBODAPP_REVISION }} --locked

      - name: Test ${{ matrix.repo }}
        run: ./test.sh ${{ matrix.repo }}
